spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    bus:
      destination: navio-config-bus
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true
