spring:
  application:
    name: api-gateway
  cloud:
    bus:
      destination: navio-config-bus
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                  - "http://localhost:3001"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: trip-planning-service
              uri: lb://trip-planning-service
              predicates:
                - Path=/v1/trips/**,/v1/public-trips/**,/v1/share/**
            - id: user-management-service
              uri: lb://user-management-service
              predicates:
                - Path=/v1/users/**,/v1/admin/users/**
            - id: mobility-and-ev-service
              uri: lb://mobility-and-ev-service
              predicates:
                - Path=/v1/places/**,/v1/routes/**,/v1/geo/**,/v1/ev/**,/v1/chargers/**,/v1/admin/ev/**
            - id: community-service
              uri: lb://community-service
              predicates:
                - Path=/v1/community/**,/v1/groups/**,/v1/posts/**,/v1/feed/**,/v1/notifications/**,/v1/media/**

eureka:
  client:
    refresh:
      enable: false
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

server:
  port: 8080
