spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tripplanner
    username: tripplanner
    password: tripplanner
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-management-service
      auto-offset-reset: earliest
    producer:
      acks: all

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

server:
  port: 8083

app:
  message: "User Management Service"
